# Generated by Django 4.2.9 on 2024-03-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(help_text='Unique identification of the Bill in Service Provider Billing System', max_length=100, unique=True, verbose_name='Bill ID')),
                ('grp_bill_id', models.CharField(help_text='Unique identification of the Group Bill in Service Provider Billing System', max_length=100, unique=True, verbose_name='Group Bill ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Normal Bill Control Number'), (2, 'Combined Bill Control Number')], default=1, verbose_name='Bill Type')),
                ('pay_type', models.PositiveSmallIntegerField(choices=[(1, 'Pay All Bill Control Numbers At Once'), (2, 'Pay any Bill Control Number')], default=1, verbose_name='Payment Type')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bill Description')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Bill Amount')),
                ('eqv_amt', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Bill Equivalent Amount')),
                ('min_amt', models.DecimalField(blank=True, decimal_places=2, help_text='The minimum amount payable value', max_digits=32, null=True, verbose_name='Minimum Payment Amount')),
                ('lim_amt', models.DecimalField(blank=True, decimal_places=2, help_text='The maximum limitation value for a transaction', max_digits=32, null=True, verbose_name='Payment Limitation Amount')),
                ('pay_lim_type', models.PositiveSmallIntegerField(choices=[(1, 'Normal Payment (No limitation)'), (2, 'All Commercial Bank Payment Limitation'), (3, 'Central Bank Limitation'), (4, 'Central Bank and Specific Commercial Bank Limitation'), (5, 'Specific Commercial Bank Limitation')], verbose_name='Bill Payment Limitation Type')),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'United States Dollar')], default='TZS', max_length=3, verbose_name='Currency Code')),
                ('exch_rate', models.DecimalField(decimal_places=2, max_digits=32)),
                ('pay_opt', models.PositiveSmallIntegerField(choices=[(1, 'FULL Bill'), (2, 'PARTIAL Bill'), (3, 'EXACT Bill'), (4, 'INFINITY payment option'), (5, 'LIMITED payment option')])),
                ('pay_plan', models.PositiveSmallIntegerField(choices=[(1, 'POST-PAID'), (2, 'PRE-PAID')], default=1, verbose_name='Payment Plan')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date when the bill was generated', verbose_name='Bill Issue Date')),
                ('expr_date', models.DateTimeField(help_text='The date when the bill will expire', verbose_name='Bill Expiry Date')),
                ('gen_by', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bill Generated By')),
                ('appr_by', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bill Approved By')),
                ('cntr_num', models.BigIntegerField(blank=True, null=True, verbose_name='Bill Control Number')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BillingDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Collection Center Name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Collection Center Code')),
                ('account_num', models.CharField(max_length=50, verbose_name='Credit Collection Account Number')),
            ],
            options={
                'verbose_name': 'Billing Department',
                'verbose_name_plural': 'Billing Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=66, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=66, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=66, verbose_name='Last Name')),
                ('tin', models.CharField(blank=True, help_text='Customer Tax Identification Number', max_length=20, null=True, verbose_name='Customer TIN')),
                ('cust_id', models.CharField(help_text='Customer Identification Reference', max_length=50, verbose_name='Customer ID')),
                ('id_type', models.CharField(help_text='Customer Identification Reference Type', max_length=50, verbose_name='Customer ID Type')),
                ('account_num', models.CharField(blank=True, help_text='Customer Account Number', max_length=50, null=True, verbose_name='Customer Account')),
                ('cell_num', models.CharField(blank=True, help_text='Customer Mobile/Cell Number should have twelve digits including country code e.g. 255XXXXXXXXX', max_length=12, null=True, verbose_name='Customer Cell Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Revenue Source Name')),
                ('gfs_code', models.CharField(max_length=20, verbose_name='GFS Code')),
                ('category', models.CharField(max_length=255, verbose_name='Revenue Category')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Revenue Sub-Category')),
            ],
            options={
                'verbose_name': 'Revenue Source',
                'verbose_name_plural': 'Revenue Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Service Provider Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Service Provider Code')),
                ('grp_code', models.CharField(max_length=10, unique=True, verbose_name='Service Provider Group Code')),
                ('sys_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_on_pay', models.CharField(default='N', help_text='The value should be “N”', max_length=1, verbose_name='Use Item Reference on Payment')),
                ('description', models.CharField(help_text='Item Description', max_length=255, verbose_name='Description')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Bill Item Quantity')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Bill Item Amount')),
                ('eqv_amt', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Bill Item Equivalent Amount')),
                ('misc_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=32, verbose_name='Bill Item Miscellaneous Amount')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill', verbose_name='Bill')),
                ('dept', models.ForeignKey(help_text='The billing department that issued the bill', on_delete=django.db.models.deletion.CASCADE, to='billing.billingdepartment', verbose_name='Billing Department')),
                ('rev_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.revenuesource', verbose_name='Revenue Source')),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
                'ordering': ['bill'],
            },
        ),
        migrations.AddField(
            model_name='billingdepartment',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.serviceprovider', verbose_name='Service Provider'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingdepartment', verbose_name='Billing Department'),
        ),
    ]
