# Generated by Django 4.2.9 on 2024-03-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['gen_date'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='gen_date',
        ),
    ]
