# Generated by Django 4.2.9 on 2024-03-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_rev_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='rev_src',
        ),
    ]
