# Generated by Django 4.2.9 on 2024-03-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_bill_rev_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='lim_amt',
            new_name='max_amt',
        ),
    ]
