# Generated by Django 4.2.9 on 2024-08-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingapikey_delete_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreconciliation',
            old_name='pay_channel',
            new_name='usd_pay_chnl',
        ),
        migrations.RemoveField(
            model_name='paymentreconciliation',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='paymentreconciliation',
            name='pay_status',
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='bill_ctr_num',
            field=models.BigIntegerField(default=0, verbose_name='Bill Control Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='bill_id',
            field=models.CharField(default=0, max_length=100, verbose_name='Bill ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='bill_pay_opt',
            field=models.CharField(default=1, max_length=10, verbose_name='Bill Payment Option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='grp_bill_id',
            field=models.CharField(default=0, max_length=100, verbose_name='Group Bill ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='qt_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unique Identification of quote transaction generated from PSP System'),
        ),
        migrations.DeleteModel(
            name='BillingAPIKey',
        ),
    ]
