# Generated by Django 4.2.9 on 2024-03-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_lim_amt_bill_max_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Bill Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='eqv_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Bill Equivalent Amount'),
        ),
    ]
