# Generated by Django 4.2.9 on 2024-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_bill_amt_alter_bill_eqv_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='expr_date',
            field=models.DateTimeField(blank=True, help_text='The date when the bill will expire', null=True, verbose_name='Bill Expiry Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pay_lim_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal Payment (No limitation)'), (2, 'All Commercial Bank Payment Limitation'), (3, 'Central Bank Limitation'), (4, 'Central Bank and Specific Commercial Bank Limitation'), (5, 'Specific Commercial Bank Limitation')], default=1, verbose_name='Bill Payment Limitation Type'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pay_opt',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FULL Bill'), (2, 'PARTIAL Bill'), (3, 'EXACT Bill'), (4, 'INFINITY payment option'), (5, 'LIMITED payment option')], default=3),
        ),
    ]
