# Generated by Django 4.2.9 on 2024-09-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_payment_id_alter_payment_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-gen_date'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.bill', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='req_ack',
            field=models.JSONField(blank=True, default=dict, verbose_name='Request Acknowledgement'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='req_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Request Data'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='req_id',
            field=models.CharField(max_length=100, verbose_name='Request ID'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='res_ack',
            field=models.JSONField(blank=True, default=dict, verbose_name='Response Acknowledgement'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='res_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Response Data'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='status_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Request Status Description'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='sys_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.systeminfo', verbose_name='Integrating System Information'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaylog',
            index=models.Index(fields=['req_id'], name='req_id_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaylog',
            index=models.Index(fields=['bill'], name='bill_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaylog',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewaylog',
            constraint=models.UniqueConstraint(fields=('req_id', 'req_type'), name='unique_request_id'),
        ),
    ]
