# Generated by Django 4.2.9 on 2024-09-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_bill_options_alter_paymentgatewaylog_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuesourceitem',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'United States Dollar'), ('EU', 'Euro')], default='TZS', max_length=3, verbose_name='Currency Code'),
        ),
    ]
