# Generated by Django 4.2.9 on 2024-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_bill_pay_lim_type_alter_bill_pay_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_lim_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal Payment (No limitation)'), (2, 'All Commercial Bank Payment Limitation'), (3, 'Central Bank Limitation'), (4, 'Central Bank and Specific Commercial Bank Limitation'), (5, 'Specific Commercial Bank Limitation')], default=1, verbose_name='Bill Payment Limitation Type'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pay_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'POST-PAID'), (2, 'PRE-PAID')], default=1, verbose_name='Payment Plan'),
        ),
    ]
