# Generated by Django 4.2.9 on 2024-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_paymentgatewaylog_req_type_cancelledbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledbill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('RECREATED', 'Recreated')], default='PENDING', max_length=10, verbose_name='Cancellation Status'),
        ),
    ]
