# Generated by Django 4.2.9 on 2024-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_bill_gen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_opt',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FULL Bill'), (2, 'PARTIAL Bill'), (3, 'EXACT Bill'), (4, 'INFINITY payment option'), (5, 'LIMITED payment option')], default=1),
        ),
    ]
