# Generated by Django 4.2.9 on 2024-09-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_bill_pay_opt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('cust_cntr_num', 'bill'), name='unique_payment'),
        ),
    ]
