# Generated by Django 4.2.9 on 2024-09-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_payment_unique_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-trx_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
