# Generated by Django 4.2.9 on 2024-10-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_paymentreconciliation_sp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Bill Description'),
        ),
    ]
