# Generated by Django 4.2.9 on 2024-10-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_cancelledbill_cust_cntr_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='penalty_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=32, verbose_name='Bill Item Penalty Amount'),
        ),
        migrations.AlterField(
            model_name='cancelledbill',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='billing.bill', verbose_name='Cancelled Bill'),
        ),
    ]
