# Generated by Django 4.2.9 on 2024-10-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_billitem_penalty_amt_alter_cancelledbill_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='trdpty_trx_id',
            field=models.CharField(blank=True, help_text='Third Party Receipt such as Issuing Bank authorization Identification, MNO Receipt, Aggregator Receipt etc.', max_length=50, null=True, verbose_name='Third Party Transaction ID'),
        ),
    ]
