# Generated by Django 4.2.9 on 2024-10-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_alter_paymentreconciliation_trdpty_trx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='Currency Symbol')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='trdpty_trx_id',
            field=models.CharField(blank=True, help_text='Third Party Receipt such as Issuing Bank authorization Identification, MNO Receipt, Aggregator Receipt etc.', max_length=50, null=True, verbose_name='Third Party Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Service Provider Transaction ID'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trx_date', models.DateField(verbose_name='Transaction Date')),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Buying Rate')),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Selling Rate')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='billing.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-trx_date'],
                'unique_together': {('currency', 'trx_date')},
            },
        ),
    ]
