# Generated by Django 4.2.9 on 2025-01-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_rename_buying_rate_exchangerate_buying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdepartment',
            name='account_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.currency', verbose_name='Account Currency'),
        ),
        migrations.AddField(
            model_name='billingdepartment',
            name='bank',
            field=models.CharField(choices=[('CRDB', 'CRDB Bank PLC'), ('NBC', 'National Bank of Commerce'), ('NMB', 'NMB Bank PLC')], default='CRDB', max_length=10, verbose_name='Bank Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingdepartment',
            name='bank_swift_code',
            field=models.CharField(default='CORUTZTZ', max_length=20, verbose_name='Bank Swift Code'),
            preserve_default=False,
        ),
    ]
