# Generated by Django 4.2.9 on 2025-01-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_alter_cancelledbill_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledbill',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='billing.bill', verbose_name='Cancelled Bill'),
        ),
    ]
