# Generated by Django 4.2.9 on 2025-12-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_performance_indexes'),
        ('billing', '0029_alter_revenuesourceitem_currency'),
    ]

    operations = [
    ]
