# Generated by Django 4.2.9 on 2025-12-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_merge_20251224_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'United States Dollar')], max_length=3, verbose_name='Currency Code'),
        ),
        migrations.CreateModel(
            name='BillingEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt')], max_length=10, verbose_name='Document type')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient email')),
                ('event_key', models.CharField(help_text='Idempotency key for the triggering event (e.g., auto:payment_confirmed, manual:{uuid})', max_length=100, verbose_name='Event key')),
                ('status', models.CharField(choices=[('NOT_SENT', 'Not sent'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('enqueued_at', models.DateTimeField(blank=True, null=True, verbose_name='Enqueued at')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Last attempt at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='Failure reason')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='billing.bill', verbose_name='Bill')),
            ],
            options={
                'verbose_name': 'Billing Email Delivery',
                'verbose_name_plural': 'Billing Email Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bill'], name='bed_bill_idx'), models.Index(fields=['status'], name='bed_status_idx'), models.Index(fields=['document_type'], name='bed_doc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='billingemaildelivery',
            constraint=models.UniqueConstraint(fields=('bill', 'document_type', 'recipient_email', 'event_key'), name='uniq_bed_bill_doc_recipient_event'),
        ),
    ]
