# Generated by Django 4.2.9 on 2026-02-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_seed_tzs_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdepartment',
            name='account_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Credit Collection Account Number'),
        ),
        migrations.AlterField(
            model_name='billingdepartment',
            name='bank',
            field=models.CharField(blank=True, choices=[('CRDB', 'CRDB Bank PLC'), ('NBC', 'National Bank of Commerce'), ('NMB', 'NMB Bank PLC')], max_length=10, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='billingdepartment',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Swift Code'),
        ),
    ]
