# Generated by Django 4.2.9 on 2026-02-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_make_dept_legacy_fields_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trx_date', models.DateField(verbose_name='Reconciliation Business Date')),
                ('req_id', models.CharField(max_length=100, unique=True, verbose_name='Request ID')),
                ('res_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Response ID')),
                ('pay_sts_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Status Code')),
                ('pay_sts_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment Status Description')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACKED', 'Acknowledged'), ('RECEIVED', 'Response Received'), ('PROCESSED', 'Processed'), ('CLOSED', 'Closed'), ('ERROR', 'Error')], default='REQUESTED', max_length=20, verbose_name='Status')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('totals_by_currency', models.JSONField(blank=True, default=dict)),
                ('internal_totals_by_currency', models.JSONField(blank=True, default=dict)),
                ('totals_match', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reconciliation Run',
                'verbose_name_plural': 'Reconciliation Runs',
                'ordering': ['-trx_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='bill_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_transactions', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='match_status',
            field=models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('AUTO_CREATED', 'Auto-created Payment'), ('MISSING_INTERNAL_PAYMENT', 'Missing internal Payment'), ('BILL_NOT_FOUND', 'Bill not found'), ('MISMATCH', 'Mismatch')], default='UNMATCHED', max_length=30, verbose_name='Match Status'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='mismatch_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_transactions', to='billing.payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliation',
            constraint=models.UniqueConstraint(fields=('payref_id',), name='uniq_recon_payref_id'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='reconciliation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.reconciliationrun'),
        ),
    ]
