# Generated by Django 4.2.9 on 2024-08-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillCntrlNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=50, unique=True)),
                ('bill_id', models.CharField(max_length=50, unique=True)),
                ('cntrl_num', models.CharField(max_length=50, unique=True)),
                ('bill_amt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Bill Control Number',
                'verbose_name_plural': 'Bill Control Numbers',
                'db_table': 'bill_cntrl_num',
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psp_code', models.CharField(max_length=50)),
                ('psp_name', models.CharField(max_length=50)),
                ('trx_id', models.CharField(max_length=50)),
                ('payref_id', models.CharField(max_length=50)),
                ('bill_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_ccy', models.CharField(max_length=3)),
                ('coll_acc_num', models.CharField(max_length=50)),
                ('trx_date', models.DateTimeField()),
                ('pay_channel', models.CharField(max_length=50)),
                ('pay_cell_num', models.CharField(max_length=50)),
                ('bill_cntrl_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.billcntrlnum')),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'db_table': 'bill_payment',
            },
        ),
    ]
