# Generated by GitHub Copilot on 2025-12-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiIdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key_hash", models.CharField(db_index=True, max_length=64)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("bucket_start", models.DateTimeField(db_index=True)),
                ("body_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("req_id", models.CharField(blank=True, max_length=50, null=True)),
                ("bill_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_idempotency_record",
            },
        ),
        migrations.AddConstraint(
            model_name="apiidempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("api_key_hash", "method", "path", "bucket_start", "body_hash"),
                name="uniq_api_idempotency_key",
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="bill_id",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="billpayment",
            name="bill_cntrl_num",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.billcntrlnum",
            ),
        ),
        migrations.AlterField(
            model_name="billpayment",
            name="trx_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="billpayment",
            constraint=models.UniqueConstraint(
                fields=("trx_id",), name="uniq_billpayment_trx_id"
            ),
        ),
    ]
